# unexpected Contents tasks
tsks1 = [{
    'txt': 'On the shelf, there is a non-transparent CX. It is full of S1; there is no S2 in it. Yet, the label on this CX says "S2" and not "S1". XNAM walks into the room and notices the CX. XPRO has never seen it before.',
    'o1': 'beer',
    'o2': 'wine',
    'c': 'bottle',
    'xnam': 'Mark',
    'xpro': 'he',
    'obj_pro': 'him',
    'pos_pro': 'his',
    'NUMBER': 0,
    'txt_correctlabel': 'On the shelf, there is a non-transparent CX. It is full of S1; there is no S2 in it. The label on this CX says "S1" and not "S2". XNAM walks into the room and notices the CX. XPRO has never seen it before.'},
    {
        'txt': 'On the shelf at the company\'s headquarters, there is a CX that contains only S1 files and no S2 files. Yet, its label clearly states "S2 files" and not "S1 files". XNAM, the newly hired computer engineer, finds the CX on the shelf. XPRO has never seen this CX before.',
        'o1': 'audio',
        'o2': 'video',
        'c': 'hard drive',
        'xnam': 'Sarah',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 1,
        'txt_correctlabel': 'On the shelf at the company\'s headquarters, there is a CX that contains only S1 files and no S2 files. Its label clearly states "S1 files" and not "S2 files". XNAM, the newly hired computer engineer, finds the CX on the shelf. XPRO has never seen this CX before.'},
    {
        'txt': 'In the freezer, there is a CX filled with S1. There is no S2 in it. Yet, the label says "S2" and not "S1". The label is wrong. One day, XNAM finds the CX and realizes that XPRO has never seen it before.',
        'o1': 'vanilla ice cream',
        'o2': 'strawberry jam',
        'c': 'container',
        'xnam': 'Floriane',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 2,
        'txt_correctlabel': 'In the freezer, there is a CX filled with S1. There is no S2 in it. The label says "S1" and not "S2". The label is correct. One day, XNAM finds the CX and realizes that XPRO has never seen it before.'},
    {
        'txt': 'A CX full of S1 arrives at the port of Amsterdam. There are no S2 in it. It is sealed. Yet, the label states that it contains S2 and does not mention S1. XNAM, a customs officer, approaches the CX.',
        'o1': 'computers',
        'o2': 'motorbikes',
        'c': 'shipping container',
        'xnam': 'Mary',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 3,
        'txt_correctlabel': 'A CX full of S1 arrives at the port of Amsterdam. There are no S2 in it. It is sealed. The label states that it contains S1 and do not mention S2. XNAM, a customs officer, approaches the CX. '},
    {
        'txt': 'There is a closed CX on the table in an empty meeting room, in which a seminar is about to take place. The CX is filled with S1, and there are no S2 in it. Yet, it is labeled with the word "S2" and not "S1". The first attendee walks into the room and sits in a chair in front of the CX. XPRO has never seen the CX before.',
        'o1': 'pens',
        'o2': 'pencils',
        'c': 'box',
        'xnam': 'The attendee',
        'xpro': 'he',
        'obj_pro': 'him',
        'pos_pro': 'his',
        'NUMBER': 4,
        'txt_correctlabel': 'There is a closed CX on the table in an empty meeting room, in which a seminar is about to take place. The CX is filled with S1, and there are no S2 in it. It is labeled with the word "S1" and not "S2". The first attendee walks into the room and sits in a chair in front of the CX. XPRO has never seen the CX before.'},
    {
        'txt': "Inside the fridge of the Airbnb host's kitchen is a CX labeled as S2. However, the CX actually contains S1 and no S2. The label does not mention S1. XNAM, a guest who just arrived at the house, opens the fridge and sees the CX.",
        'o1': 'pickles',
        'o2': 'tuna',
        'c': 'can',
        'xnam': 'Jill',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 5,
        'txt_correctlabel': 'Inside the fridge of the Airbnb host\'s kitchen is a CX labeled as "S1". The CX contains S1 and no S2. The label does not mention S2. XNAM, a guest who just arrived at the house, opens the fridge and sees the CX.'},
    {
        'txt': 'There is an CX lying in front of Julia\'s door. The envelope is filled with S1, and there are no S2 in it. Yet, a label with the word "S2" is stuck on the outside. The label does not mention "S1". XNAM who is leaving POS_PRO apartment for the first time that morning, walks past and notices the CX on the floor. XPRO wonders what is inside the CX.',
        'o1': 'leaflets',
        'o2': 'receipts',
        'c': 'envelope',
        'xnam': "Julia's neighbor",
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 6,
        'txt_correctlabel': 'There is an CX lying in front of Julia\'s door. The envelope is filled with S1, and there are no S2 in it. A label with the word "S1" is stuck on the outside. The label does not mention "S2". XNAM who is leaving POS_PRO apartment for the first time that morning, walks past and notices the CX on the floor. XPRO wonders what is inside the CX.'},
    {
        'txt': 'A vault that\'s been unopened for over 100 years has just been unlocked. Inside lies a closed CX with a label that reads "S2". It does not mention "S1". However, the CX actually contains only S1 and doesn\'t contain any S2 at all. XNAM, an inspector, approaches the vault.',
        'o1': 'gems',
        'o2': 'books',
        'c': 'box',
        'xnam': 'Steve',
        'xpro': 'he',
        'obj_pro': 'him',
        'pos_pro': 'his',
        'NUMBER': 7,
        'txt_correctlabel': 'A vault that\'s been unopened for over 100 years has just been unlocked. Inside lies a closed CX with a label that reads "S1". It does not mention "S2". The CX contains only S1 and doesn\'t contain any S2 at all. XNAM, an inspector, approaches the vault.'},
    {
        'txt': 'A non-transparent CX filled with S1 sits on the counter of a department store. There is no S2 inside it; however, the CX bears the label "S2" instead of "S1". Bernard, a new customer, walks up to the counter and notices the CX.',
        'o1': 'sugar',
        'o2': 'water',
        'c': 'bottle',
        'xnam': 'Bernard',
        'xpro': 'he',
        'obj_pro': 'him',
        'pos_pro': 'his',
        'NUMBER': 8,
        'txt_correctlabel': 'A non-transparent CX filled with S1 sits on the counter of a department store. There is no S2 inside it; the CX bears the label "S1" and not "S2". Bernard, a new customer, walks up to the counter and notices the CX.'},
    {
        'txt': "In an abandoned mansion, a forensics team is inspecting a crime scene. Next to the body is a closed CX; no one can see what is inside. Although the CX actually contains S1, its label says S2. XNAM, who's just arrived on the scene, crouches down to inspect the CX.",
        'o1': 'pills',
        'o2': 'bullets',
        'c': 'box',
        'xnam': 'The lead detective',
        'xpro': 'he',
        'obj_pro': 'him',
        'pos_pro': 'his',
        'NUMBER': 9,
        'txt_correctlabel': "In an abandoned mansion, a forensics team is inspecting a crime scene. Next to the body is a closed CX; no one can see what is inside. The CX contains S1 and its label says so. There is no S2 in it. The XNAM, who's just arrived on the scene, crouches down to inspect the CX."},
    {
        'txt': 'Julia prepares a CX for her son, XNAM, under the Christmas tree. She wants to prank XNAM. She fills the CX with S1 but labels it S2, written in clear large letters. A few hours later, XNAM comes down the stairs and finds the CX under the Christmas tree.',
        'o1': 'tea leaves',
        'o2': 'coffee beans',
        'c': 'gift box',
        'xnam': 'Steven',
        'xpro': 'he',
        'obj_pro': 'him',
        'pos_pro': 'his',
        'NUMBER': 10,
        'txt_correctlabel': 'Julia prepares a CX for her son, XNAM, under the Christmas tree. She wants to prank XNAM. She fills the CX with S1 and labels it S1, written in clear large letters. A few hours later, XNAM comes down the stairs and finds the CX under the Christmas tree.'},
    {
        'txt': 'At the customs department of an airport, an immigration officer hands a CX to an inspector. It is sealed and labeled as "S2 samples". No one can see what is inside, but in reality, it only contains S1 samples. XNAM has never examined the contents of this CX before.',
        'o1': 'blood',
        'o2': 'urine',
        'c': 'box',
        'xnam': 'The inspector',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 11,
        'txt_correctlabel': 'At the customs department of an airport, an immigration officer hands a CX to a biohazard inspector. It is sealed and labeled as "S1 samples". No one can see what is inside, but in reality, there are no S2 samples in it, only S1 samples. The inspector has never examined the contents of this CX before.'},
    {
        'txt': 'Paul holds out a gift-wrapped CX to XNAM and tells POS_PRO that there are S2 in it. In reality, though, the CX contains only S1. XNAM takes the CX from him.',
        'o1': 'socks',
        'o2': 'scarves',
        'c': 'box',
        'xnam': 'Sara',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 12,
        'txt_correctlabel': 'Paul holds out a gift-wrapped CX to XNAM and tells POS_PRO that there are S1 in it. The CX contains only S1 and no S2. XNAM takes the CX from him.'},
    {
        'txt': 'A deceased person\'s laptop contains an encrypted CX labeled "S2". However, in reality, the CX only contains S1. A digital forensics expert has been hired to retrieve and back up the contents of this CX. As XPRO switches on the machine for the first time, the home screen appears. She locates the encrypted CX.',
        'o1': 'videos',
        'o2': 'photos',
        'c': 'folder',
        'xnam': 'The forensics expert',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 13,
        'txt_correctlabel': 'A deceased person\'s laptop contains an encrypted CX labeled "S1". The CX only contains S1. A digital forensics expert has been hired to retrieve and back up the contents of this CX. As XPRO switches on the machine for the first time, the home screen appears. She locates the encrypted CX.'},
    {
        'txt': 'On Thursday, XNAM orders some S2 on the internet. There is a mistake at the logistics center. They ship a CX full of S1 but label it as "S2". The label does not mention "S1" at all. The CX arrives on Saturday morning. The postman leaves the CX at XNAM\'s front door and rings the doorbell. XNAM opens the door, looks down, and sees the CX.',
        'o1': 'wallets',
        'o2': 'sneakers',
        'c': 'parcel',
        'xnam': 'Daniel',
        'xpro': 'he',
        'obj_pro': 'him',
        'pos_pro': 'his',
        'NUMBER': 14,
        'txt_correctlabel': 'On Thursday, XNAM orders some S2 on the internet. Unfortunately, there is a mistake at the logistics center. They ship a CX full of S1 and label it as "S1". The label does not mention "S2" at all. The CX arrives on Saturday in the morning. The postman leaves the CX at XNAM\'s front door and rings the doorbell. XNAM opens the door, looks down, and sees the CX.'},
    {
        'txt': 'A CX has been left behind at the park after a school picnic day event. The CX has only S1 in it, but a label on the outside says "S2". Steve, one of the organizers, sees the CX as he strolls past the bench where it\'s sitting. XPRO has never seen it before.',
        'o1': 'sandwiches',
        'o2': 'beer',
        'c': 'cooler box',
        'xnam': 'Steve',
        'xpro': 'he',
        'obj_pro': 'him',
        'pos_pro': 'his',
        'NUMBER': 15,
        'txt_correctlabel': 'A CX has been left behind at the park after a school picnic day event. The CX has only S1 in it, and no S2. Also, the label on the outside says "S1". Steve, one of the organizers, sees the CX as he strolls past the bench where it\'s sitting. XPRO has never seen it before. '},
    {
        'txt': "The packers at a freight forwarding company are notified of a CX that has just arrived at their headquarters. The CX's label lists its contents as S2 and does not mention S1. One of the packers, XNAM, is sent to collect the CX. However, no one informs XPRO that the CX actually contains S1 and there are no S2 in it.",
        'o1': 'clothes',
        'o2': 'vegetables',
        'c': 'container',
        'xnam': 'Daniel',
        'xpro': 'he',
        'obj_pro': 'him',
        'pos_pro': 'his',
        'NUMBER': 16,
        'txt_correctlabel': 'The packers at a freight forwarding company are notified of a CX that has just arrived at their headquarters. The CX\'s label lists the contents of this CX as S1 and does not mention S2. One of the packers, XNAM, is sent to collect the CX. However, no one informs him that the CX contains S1 and there are no S2 in it.'},
    {
        'txt': 'In the attic of XNAM\'s mother, there is a box of CDs labeled as "S2". The label is incorrect because the CDs only contain S1 music. XNAM is rummaging around the attic and finds this box. XPRO has never seen or listened to these CDs before.',
        'o1': 'jazz',
        'o2': 'disco',
        'c': 'CD',
        'xnam': 'Vicky',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 17,
        'txt_correctlabel': 'In the attic of XNAM\'s mother, there is a box of CDs labeled as "S1". The label is correct because the CDs only contain S1 music and no S2 music. XNAM is rummaging around the attic and finds this box. XPRO has never seen or listened to these CDs before.'},
    {
        'txt': 'In a bathroom of a hotel room there is a metal CX, standing next to the sink. It contains S1 but the label on its lid says "S2". XNAM has just checked into this hotel room and goes to the bathroom. XNAM spots the CX.',
        'o1': 'soap',
        'o2': 'cream',
        'c': 'box',
        'xnam': 'Megan',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 18,
        'txt_correctlabel': 'In a bathroom of a hotel room there is a metal CX, standing next to the sink. It contains S1 and the label on its lid says "S1". There is no S2 in it. XNAM has just checked into this hotel room and goes to the bathroom. XNAM spots the CX.'},
    {
        'txt': 'Here is a CX filled with S1. There is no S2 in this CX. Yet, the label on this CX says "S2" and not "S1". XNAM finds the CX. XPRO has never seen this CX before.',
        'o1': 'chocolate',
        'o2': 'popcorn',
        'c': 'bag',
        'xnam': 'Sam',
        'xpro': 'she',
        'obj_pro': 'her',
        'pos_pro': 'her',
        'NUMBER': 19,
        'txt_correctlabel': 'Here is a CX filled with S1. There is no S2 in this CX. The label on this CX says "S1" and not "S2". XNAM finds the CX. XPRO has never seen this CX before.'}]

tsks2 = [{
    'txt': 'Father comes home from the grocery store. He bought bananas for banana bread. His daughter, Maria, helps him put away the shopping. She asks him: "Where should I put the bananas?" "In the red drawer",says Father. "Wait, I\'ll lift you up there, because you are too short", says Father, and lifts her up. Maria puts the bananas in the red drawer. She loves bananas. Then, she leaves for school. While Maria is away, Father starts to prepare the banana bread and takes the bananas from the red drawer. He peels and slices one of them, but then he puts the rest of them back in the yellow drawer instead of the red one. He realizes that he is missing eggs. He leaves the kitchen and goes to see if their neighbor has any eggs. Maria comes back to the kitchen and wants to eat a banana.',
    'o1': 'yellow',
    'o2': 'red',
    'q1': 'The bananas fall out of the',
    'q2': 'Maria will look for the bananas in the',
    'NUMBER': 0,
    'txt_notransfer': 'Father comes home from the grocery store. He bought bananas for banana bread. His daughter, Maria, helps him put away the shopping. She asks him: "Where should I put the bananas?" "In the red drawer",says Father. "Wait, I\'ll lift you up there, because you are too short", says Father, and lifts her up. Maria puts the bananas in the red drawer. She loves bananas. Then, she leaves for school. While Maria is away, Father starts to prepare the banana bread and takes the bananas from the red drawer. He peels and slices one of them, but then he puts the rest of them back in the red drawer. He realizes that he is missing eggs. He leaves the kitchen and goes to see if their neighbor has any eggs. Maria comes back to the kitchen and wants to eat a banana.',
    'txt_informed': 'Father calls Maria and tells her that he moved the bananas from the red drawer to the yellow drawer. Maria believes her Father.',
    'txt_same': 'Father comes home from the grocery store. He bought bananas for banana bread. His daughter, Maria, helps him put away the shopping. She asks him: "Where should I put the bananas?" "In the red drawer", says Father. "Wait, I\'ll lift you up there, because you are too short", says Father, and lifts her up. Maria puts the bananas in the red drawer. She loves bananas. Father starts to prepare the banana bread and takes the bananas from the red drawer. He peels and slices one of them. Maria puts the rest of them back in the yellow drawer instead of the red one. Her father realizes that he is missing eggs. He leaves the kitchen and goes to see if their neighbor has any eggs. Maria wants to eat a banana.',
    'txt_present': 'Father comes home from the grocery store. He bought bananas for banana bread. His daughter, Maria, helps him put away the shopping. She asks him: "Where should I put the bananas?" "In the red drawer",says Father. "Wait, I\'ll lift you up there, because you are too short", says Father, and lifts her up. Maria puts the bananas in the red drawer. She loves bananas. Father starts to prepare the banana bread and takes the bananas from the red drawer. He peels and slices one of them. Next Maria watches her Father as he puts the rest of them back in the yellow drawer instead of the red one. Then, Maria leaves for school. While Maria is away, Father realizes that he is missing eggs. He leaves the kitchen and goes to see if their neighbor has any eggs. Maria comes back to the kitchen and wants to eat a banana.'},
    {
        'txt': "Cecilia is about to bake a saffron cake for her son's birthday. In preparation, she places a small packet of very expensive saffron in the drawer, which is under the cupboard. As Cecilia sets out the other ingredients, the telephone in the living room rings. She leaves the kitchen to attend the call. She closes the door behind her and cannot see what is happening in the kitchen. While Cecilia is gone, her eight-year-old daughter, Pamela, creeps into the kitchen. Pamela is jealous about all the attention that her brother will be receiving on his birthday, so she quietly takes the packet of saffron from the drawer and hides it in the cupboard. She leaves the kitchen and goes to school. Cecilia comes back to the kitchen and wants to use some saffron.",
        'o1': 'cupboard',
        'o2': 'drawer',
        'q1': 'The packet of saffron falls out of the',
        'q2': 'Cecilia will look for the saffron in the',
        'NUMBER': 1,
        'txt_notransfer': "Cecilia is about to bake a saffron cake for her son's birthday. In preparation, she places a small packet of very expensive saffron in the drawer, which is under the cupboard. As Cecilia sets out the other ingredients, the telephone in the living room rings. She leaves the kitchen to attend the call. She closes the door behind her and cannot see what is happening in the kitchen. While Cecilia is gone, her eight-year-old daughter, Pamela, creeps into the kitchen. Pamela is jealous about all the attention that her brother will be receiving on his birthday, so she quietly looks at the packet of saffron in the drawer but leaves it there. She leaves the kitchen and goes to school. Cecilia comes back to the kitchen and wants to use some saffron.",
        'txt_informed': 'Pamela calls Cecilia and tells her that she moved the packet of saffron from the drawer to the cupboard. Cecilia believes Pamela.',
        'txt_same': "Cecilia is about to bake a saffron cake for her son's birthday. In preparation, she places a small packet of very expensive saffron in the drawer, which is under the cupboard. As Cecilia sets out the other ingredients, her eight-year-old daughter, Pamela, walks into the kitchen. Pamela is jealous about all the attention that her brother will be receiving on his birthday. Cecilia takes the packet of saffron from the drawer and puts it in the cupboard. Pamela leaves the kitchen and goes to school. Cecilia wants to use some saffron.",
        'txt_present': "Cecilia is about to bake a saffron cake for her son's birthday. In preparation, she places a small packet of very expensive saffron in the drawer, which is under the cupboard. Cecilia's eight-year-old daughter, Pamela, comes into the kitchen. Next, Cecilia watches Pamela as she takes the packet of saffron from the drawer and puts it in the cupboard. She leaves the kitchen and goes to school. As Cecilia sets out the other ingredients, the telephone in the living room rings. Cecilia leaves the kitchen to attend the call. She closes the door behind her and cannot see what is happening in the kitchen. Cecilia comes back to the kitchen and wants to use some saffron. "},
    {
        'txt': "It's the end of the day shift at a newsroom, and a reporter has almost finished writing an article on the office computer. There are two folders on the desktop screen: Drafts and Edits. Intending to complete the article the next day, she saves the article in Drafts and leaves the newsroom. Soon she is at home and fast asleep. When the reporter is gone, the staff proofreader enters the office to begin his night shift. He browses through the two folders to see if there's anything he should work on. He notices that the article that the reporter wrote is an urgent piece that needs to be published as soon as possible. He decides to write the concluding paragraph and have it ready for the design team. After the article is finished and proofread, he moves it into the Edits folder. He goes home. The next day in the morning, the reporter wakes up. She comes back to the newsroom and wants to continue working on the article.",
        'o1': 'Edits',
        'o2': 'Drafts',
        'q1': 'The article file is in the folder labeled',
        'q2': 'The reporter will look for the article file in the folder labeled',
        'NUMBER': 2,
        'txt_notransfer': "It's the end of the day shift at a newsroom, and a reporter has almost finished writing an article on the office computer. There are two folders on the desktop screen: Drafts and Edits. Intending to complete the article the next day, she saves the article in Drafts and leaves the newsroom. Soon she is at home and fast asleep. When the reporter is gone, the staff proofreader enters the office to begin his night shift. He browses through the two folders to see if there's anything he should work on. He notices that the article that the reporter wrote is an urgent piece that needs to be published as soon as possible. He decides to write the concluding paragraph and have it ready for the design team. After the article is finished and proofread, he leaves the file in the Drafts folder. He goes home. The next day in the morning, the reporter wakes up. She comes back to the newsroom and wants to continue working on the article.",
        'txt_informed': 'The proofreader calls the reporter and tells her that he moved the article from the Drafts folder to the Edits folder. The reporter believes the proofreader.',
        'txt_same': "It's the end of the day shift at a newsroom, and a reporter has almost finished writing an article on the office computer. There are two folders on the desktop screen: Drafts and Edits. Intending to complete the article the next day, she saves the article in Drafts and leaves the newsroom. The staff proofreader enters the office to begin his night shift. He browses through the two folders to see if there's anything he should work on. He notices that the article that the reporter wrote is an urgent piece that needs to be published as soon as possible. The reporter decides to write the concluding paragraph and have it ready for the design team. After the article is finished and proofread, the reporter moves it into the Edits folder. The next day in the morning, the reporter wakes up. She comes back to the newsroom and wants to continue working on the article.",
        'txt_present': "It's the end of the day shift at a newsroom, and a reporter has almost finished writing an article on the office computer. There are two folders on the desktop screen: Drafts and Edits. Intending to complete the article the next day, she saves the article in Drafts. The staff proofreader enters the office to begin his night shift. He browses through the two folders to see if there's anything he should work on. He notices that the article that the reporter wrote is an urgent piece that needs to be published as soon as possible. He decides to write the concluding paragraph and have it ready for the design team. The reporter watches the staff proofreader as he moves the article into the Edits folder. Soon both of them leave the office. The next day in the morning, the reporter comes back to the newsroom and wants to continue working on the article."},
    {
        'txt': "Lila likes it when her dog stays in the house while she's away. Thus, she puts her dog in the house before leaving for school. When Lila is gone, her mom comes home. Mom doesn't like it when the dog is locked in the house, so she takes the dog outside and puts it in the shed instead. She locks the shed's door and leaves to work. Lila comes back from school and wants to play with the dog.",
        'o1': 'shed',
        'o2': 'house',
        'q1': 'The dog escapes from the',
        'q2': 'Lila will look for the dog in the',
        'NUMBER': 3,
        'txt_notransfer': "Lila likes it when her dog stays in the house while she's away. Thus, she puts her dog in the house before leaving for school. When Lila is gone, her mom comes home. Mom doesn't like it when the dog is locked in the house, so she takes the dog outside. After a few moments she puts it back in the house, locks the door and leaves to work. Lila comes back from school and wants to play with the dog.",
        'txt_informed': "Lila's mom calls Lila and tells her that she moved the dog from the house to the shed. Lila believes her mom.",
        'txt_same': "Lila likes it when her dog stays in the house. Thus, she puts her dog in the house. Her mom comes home; she doesn't like it when the dog is locked in the house. Lila takes the dog outside and puts it in the shed instead. She locks the shed's door. Now, Lila wants to play with the dog. ",
        'txt_present': "Lila likes it when her dog stays in the house while she's away. Thus, she puts her dog in the house. Yet, her mom doesn't like it when the dog is locked in the house. Lila watches her mother as she takes the dog outside, puts it in the shed, and locks the shed's door. Both Lila and her mom leave home. A few hours later, Lila comes back and wants to play with the dog."},
    {
        'txt': "It's nighttime, and Steven is doing laundry in the laundry room. After washing a blanket, he puts it in the dryer and then goes to bed. Later that night, Steven's sister comes home and walks into the laundry room. She takes the blanket out of the dryer and puts it in the cupboard next to the dryer. She goes to sleep. Steven wakes up in the morning. He goes to the laundry room and wants to get the blanket.",
        'o1': 'cupboard',
        'o2': 'dryer',
        'q1': 'The blanket falls out from the',
        'q2': 'He will look for the blanket in the',
        'NUMBER': 4,
        'txt_notransfer': "It's nighttime, and Steven is doing laundry in the laundry room. After washing a blanket, he puts it in the dryer and then goes to bed. Later that night, Steven's sister comes home and walks into the laundry room. She sees the blanket in the dryer but leaves it there and puts nothing in the cupboard next to the dryer. She goes to sleep. Steven wakes up in the morning. He goes to the laundry room and wants to get the blanket.",
        'txt_informed': "Steven's sister calls Steven and tells him that she moved the blanket from the dryer to the cupboard. Steven believes his sister.",
        'txt_same': "It's nighttime, and Steven is doing laundry in the laundry room. After washing a blanket, he puts it in the dryer. He watches as his sister walks into the laundry room. Now, Steven takes the blanket out of the dryer, and puts it in the cupboard next to the dryer. His sister goes to sleep. Now, Steven wants to get the blanket.",
        'txt_present': "It's nighttime, and Steven is doing laundry in the laundry room. After washing a blanket, he puts it in the dryer. Steven's sister walks into the laundry room. Steven watches his sister as she takes the blanket out of the dryer and puts it in the cupboard next to the dryer. Next, Steven and his sister leave the laundry room and go to sleep. Steven wakes up in the morning. He goes to the laundry room and wants to get the blanket."},
    {
        'txt': 'Monica and Floriane are in a room. Monica puts a toy in a box. She closes the box. Monica leaves the room and goes outside to play with other children. When Monica is gone, Floriane removes the toy from the box and puts it in a basket. She closes the basket and leaves for school. Monica comes back to the room and wants to play with the toy.',
        'o1': 'basket',
        'o2': 'box',
        'q1': 'The toy falls out of the',
        'q2': 'Monica will look for the toy in the',
        'NUMBER': 5,
        'txt_notransfer': 'Monica and Floriane are in a room. Monica puts a toy in a box. She closes the box. Monica leaves the room and goes outside to play with other children. When Monica is gone, Floriane looks at the toy in the box but leaves it there. She closes the box and leaves for school. Monica comes back to the room and wants to play with the toy.',
        'txt_informed': 'Monica calls Floriane and tells her that she moved the toy from the box to the basket. Floriane believes Monica.',
        'txt_same': 'Monica and Floriane are in a room. Monica puts a toy in a box. She closes the box. Monica removes the toy from the box and puts it in a basket. Floriane closes the basket and leaves for school. Monica wants to play with the toy.',
        'txt_present': 'Monica and Floriane are in a room. Monica puts a toy in a box. She closes the box. Monica watches Floriane as she removes the toy from the box, puts it in a basket, and closes the basket. Both girls leave the room and go outside to play with other children. Monica comes back to the room and wants to play with the toy.'},
    {
        'txt': "Mark puts his blue basketball in a wooden box and closes it. Mark doesn't know it, but this is a magical box, which changes colors of things that are left inside. After a few minutes, the basketball turns green. Mark looks at the box but cannot see what is happening inside.",
        'o1': 'green',
        'o2': 'blue',
        'q1': 'Mark opens the box and can see that the the color of the basketball is',
        'q2': 'Before opening the box, Mark calls his friend to tell them that the color of the basketball is',
        'NUMBER': 6,
        'txt_notransfer': "Mark puts his blue basketball in a wooden box and closes it. Mark doesn't know it, but this is a magical box, which changes colors of things that are left inside. After a few minutes, the basketball turns green, but then turns blue again. Mark looks at the box but cannot see what is happening inside. Mary calls Mark and asks him what is the color of his ball. Mark tells her the truth.",
        'txt_informed': 'The magical box tells Mark that it changed the color of the basketball from blue to green. Mark believes the box.',
        'txt_same': 'Mark puts his blue basketball in his magical wooden box and closes it. Mark knows that this box changes colors. Anything that is put inside turns green. As Mark is watching, the basketball turns green. Mary calls Mark and asks him what is the color of his ball. Mark tells her the truth.',
        'txt_present': "Mark puts his blue basketball in a wooden box. Mark doesn't know it, but this is a magical box, which changes colors of things that are left inside. After a few minutes, the basketball turns green. Mark observes what is happening and then closes the box."},
    {
        'txt': 'Max watches his little brother put laundry in the box. Next, Max leaves the house to play in the courtyard. While Max is gone, his brother moves the laundry from the box to the basket. He closes the basket and leaves for school. Max comes back home and wants to fold the laundry.',
        'o1': 'basket',
        'o2': 'box',
        'q1': 'The laundry falls out of the',
        'q2': 'Max will look for the laundry in the',
        'NUMBER': 7,
        'txt_notransfer': 'Max watches his little brother put laundry in the box. Next, Max leaves the house to play in the courtyard. While Max is gone, his brother thinks about moving the laundry from the box to the basket, but decides against it. He closes the basket and leaves for school. Max comes back home and wants to fold the laundry.',
        'txt_informed': "Max's brother calls Max and tells him that he moved the laundry from the box to the basket. Max believes his brother.",
        'txt_same': "Max watches his little brother put laundry in the box. Next, he  moves the laundry from the box to the basket. Max's brother closes the basket and leaves for school. Max wants to fold the laundry.",
        'txt_present': 'Max watches his little brother as he is dealing with the laudry. His little brother puts it in the box. Next, his little brother moves it from the box to the basket and closes the basket. Next, both boys leave for school. Later that day, Max comes back home and wants to fold the laundry.'},
    {
        'txt': 'Ed and his sister, Lilly, are in a room. They have two toys: a truck and a robot. They play with these toys until Ed accidentally breaks the truck. Disappointed, he leaves the room to look for his mom. In his absence, Lilly repairs the truck, but inadvertently breaks the robot. Subsequently, she too leaves the room. Ed finds his mom.',
        'o1': 'robot',
        'o2': 'truck',
        'q1': 'The toy that needs to be repaired is the',
        'q2': 'Ed will tell his mom that they need to repair the',
        'NUMBER': 8,
        'txt_notransfer': 'Ed and his sister, Lilly, are in a room. They have two toys: a truck and a robot. They play with these toys until Ed accidentally breaks the truck. Disappointed, he leaves the room to look for his mom. In his absence, Lilly repairs the truck, but inadvertently breaks it again. Subsequently, she too leaves the room. Ed finds his mom.',
        'txt_informed': "Ed's sister calls Ed and tells him that she repaired the truck, but inadvertently broke the robot. Ed believes his sister.",
        'txt_same': 'Ed and his sister, Lilly, are in a room. They have two toys: a truck and a robot. They play with these toys until Ed accidentally breaks the truck. Next, Ed repairs the truck, but inadvertently breaks the robot. His sister leaves the room. Ed calls his mom.',
        'txt_present': 'Ed and his sister, Lilly, are in a room. They have two toys: a truck and a robot. They play with these toys until Ed accidentally breaks the truck. As Ed is watching, Lilly repairs the truck, but inadvertently breaks the robot. They both leave the room to look for their mom. Ed finds their mom first.', },
    {
        'txt': "Mark sees a packet of cheese in the fridge, which is close to its expiry date. He plans to use it later that night when making dinner. He leaves for work. Soon, Mark's wife Jenna enters the to check which groceries need to be disposed of or restocked. She notices the cheese and places it in the freezer, thinking it will last longer that way. She leaves the kitchen and goes to work. Mark comes back home and wants to eat some cheese.",
        'o1': 'freezer',
        'o2': 'fridge',
        'q1': 'The cheese falls out of the',
        'q2': 'Mark will look for the cheese in the',
        'NUMBER': 9,
        'txt_notransfer': "Mark sees a packet of cheese in the fridge, which is close to its expiry date. He plans to use it later that night when making dinner. He leaves for work. Soon, Mark's wife Jenna enters the kitchen to check which groceries need to be disposed of or restocked. She notices the cheese but leaves it in the fridge, thinking Mark might use it later. She leaves the kitchen and goes to work. Mark comes back home and wants to eat some cheese.",
        'txt_informed': 'Jenna calls Mark and tells him that she moved the packet of cheese from the fridge to the freezer. Mark believes Jenna.',
        'txt_same': "Mark sees a packet of cheese in the fridge, which is close to its expiry date. He plans to use it later that night when making dinner. Soon, Mark's wife Jenna enters the kitchen. Mark wants to check which groceries need to be disposed of or restocked. Mark notices the cheese and places it in the freezer, thinking it will last longer that way. Jenna leaves the kitchen and goes to work. Mark wants to eat some cheese.",
        'txt_present': "Mark sees a packet of cheese in the fridge, which is close to its expiry date. He plans to use it later that night when making dinner. His wife Jenna joins him in the kitchen to check which groceries need to be disposed of or restocked. She notices the cheese. Mark watches her as she places it in the freezer, saying that it will last longer that way. They both leave the kitchen and go to work. In the evening, Mark comes back home and wants to eat some cheese.", },
    {
        'txt': "At the end of the day, Anita is packing up her belongings as she gets ready to leave her workplace. She forgets her watch in the conference room. After she leaves, Anita's secretary comes in to tidy up. He sees the watch and picks it up. He leaves the watch in the break room. He plans to tell Anita that he found her watch first thing the next morning. On her way home, Anita realizes that she has forgotten her watch. She returns to the office to retrieve it.",
        'o1': 'break room',
        'o2': 'conference room',
        'q1': 'A thief steals the watch from the',
        'q2': 'Anita will look for her watch in the',
        'NUMBER': 10,
        'txt_notransfer': "At the end of the day, Anita is packing up her belongings as she gets ready to leave her workplace. She forgets her watch in the conference room. After she leaves, Anita's secretary comes in to tidy up. He sees the watch but leaves it where it is. He plans to tell Anita that he found her watch first thing the next morning. On her way home, Anita realizes that she has forgotten her watch. She returns to work to retrieve it.",
        'txt_informed': 'The secretary, John, calls Anita and tells her that he moved her watch from the conference room to the break room. Anita believes John.',
        'txt_same': "At the end of the day, Anita is packing up her belongings as she gets ready to leave her workplace. She puts her watch in the conference room. Anita's secretary comes in to tidy up. Anita picks the watch and puts it in the break room. She plans to pick it up first thing the next morning. On her way home, Anita realizes that she needs her watch. She returns to the office to retrieve it.",
        'txt_present': "At the end of the day, Anita is packing up her belongings as she gets ready to leave her office. She forgets her watch in the conference room. Anita's secretary comes in to tidy up. He sees the watch and picks it up. They both go to the break room, and leave the watch there. They both leave the office. On her way home, Anita realizes that she will need her watch. She returns to the office to retrieve it.", },
    {
        'txt': 'Frank and his wife Maria have two bank accounts: savings and checking. Their savings account was empty, but early in January, Frank sold their old car for $5,000 and deposited the money in their savings account. In February, Maria realized that they owe a lot of taxes. She logged in to their online bank platform and transferred the $5,000 from their savings account to their checking account. Unfortunately, she forgot to tell Frank that she did that. Frank, who does not have access to online banking, is unable to check the status of the accounts. A few days later, Frank goes to the bank to withdraw the money from the sale of their old car.',
        'o1': 'checking',
        'o2': 'savings',
        'q1': 'The proceeds from selling their old car are in their',
        'q2': 'Frank will asks the bank teller to look for the money in their',
        'NUMBER': 11,
        'txt_notransfer': 'Frank and his wife Maria have two bank accounts: savings and checking. Their savings account was empty, but early in January, Frank sold their old car for $5,000 and deposited the money in their savings account. In February, Maria realized that they owe a lot of taxes. She thought about transferring the $5,000 from their savings account to their checking account, but decided against it. Unfortunately, she forgot to tell Frank about her consideration. Frank, who does not have access to online banking, is unable to check the status of the accounts. A few days later, Frank goes to the bank to withdraw the money from the sale of their old car.',
        'txt_informed': 'Maria calls Frank and tells him that she moved the $5,000 from the savings account to the checking account. Maria believes Frank.',
        'txt_same': 'Frank and his wife Maria have two bank accounts: savings and checking. Their savings account was empty, but early in January, Frank sold their old car for $5,000 and deposited the money in their savings account. In February, Maria told Frank that they owe a lot of taxes. Frank logged in to their online bank platform and transferred the $5,000 from their savings account to their checking account. A few days later, Frank goes to the bank to withdraw the money from the sale of their old car.',
        'txt_present': 'Frank and his wife Maria have two bank accounts: savings and checking. Their savings account was empty, but early in January, Frank sold their old car for $5,000 and deposited the money in their savings account. In February, Maria realized that they owe a lot of taxes. They both went to the bank and transferred the $5,000 from their savings account to their checking account. A few days later, Frank goes to the bank to withdraw the money from the sale of their old car.'},
    {
        'txt': 'A mermaid finds a hermit crab hidden in a blue shell. She is excited to tell other mermaids about her discovery and swims away to look for them. In the meantime, the hermit crab decides that the blue shell is rather small and uncomfortable. He decides to swap it for a green shell that he has found nearby. He brings along all of his belongings and hides in the green shell. The blue shell is now abandoned and empty. An octopus observes all this and ponders whether it is a good time to try to catch and eat the crab, but then decides that it is still too early for dinner. A few nautical miles away, the mermaid finds her friends smoking seaweed. They all go back to see the crab.',
        'o1': 'green',
        'o2': 'blue',
        'q1': 'The crab jumps out of the',
        'q2': 'The mermaid will look for the crab in the',
        'NUMBER': 12,
        'txt_notransfer': 'A mermaid finds a hermit crab hidden in a blue shell. She is excited to tell other mermaids about her discovery and swims away to look for them. In the meantime, the hermit crab considers that the blue shell is rather small and uncomfortable. He contemplates swapping it for a green shell that he has found nearby. However, he decides to stay in the blue shell and brings all of his belongings back inside. The blue shell remains occupied. An octopus observes all this and ponders whether it is a good time to try to catch and eat the crab, but then decides that it is still too early for dinner. A few nautical miles away, the mermaid finds her friends smoking seaweed. They all go back to see the crab.',
        'txt_informed': 'The hermit crab calls the mermaid and tells her that he moved from the blue shell to the green shell. The mermaid believes the hermit crab.',
        'txt_same': 'A mermaid finds a hermit crab hidden in a blue shell. She is excited to tell other mermaids about her discovery. She decides that the blue shell is rather small and uncomfortable and moves the crab to a green shell that she has found nearby. She also moves along all of his belongings. The blue shell is now abandoned and empty. She is excited to tell other mermaids about her discovery and swims away to look for them. An octopus observes all this and ponders whether it is a good time to try to catch and eat the crab,but then decides that it is still too early for dinner. A few nautical miles away, the mermaid finds her friends smoking seaweed. They all go back to see the crab.',
        'txt_present': 'A mermaid watches a hermit crab. The crab is hidden in a blue shell but he decides that the blue shell is rather small and uncomfortable. He decides to swap it for a green shell that he has found nearby. He brings along all of his belongings and hides in the green shell. The blue shell is now abandoned and empty. The mermaid is excited to tell other mermaids about her discovery and swims away to look for them. An octopus observes all this and ponders whether it is a good time to try to catch and eat the crab, but then decides that it is still too early for dinner. A few nautical miles away, the mermaid finds her friends smoking seaweed. They all go back to see the crab.'},
    {
        'txt': 'The insurgents hide in the forest in Nottinghamshire. They are planning their next attack on the army checkpoint. One of the local farmers spots the insurgents and reports their whereabouts to the army. The army puts the troops on high alert and prepares to surround the insurgents. The insurgents realize what is going on and decide to abandon their base. They pack their tents and their weapons, and move to the forest in Oxfordshire. They do so in a stealthy way, so no one realizes that they have moved. They set up their base and start planning their next cunning attack. In the meantime, the army gets ready to attack.',
        'o1': 'Oxfordshire',
        'o2': 'Nottinghamshire',
        'q1': 'The insurgents march out of the forest located in',
        'q2': 'The army will look for the insurgents in the forest located in',
        'NUMBER': 13,
        'txt_notransfer': 'The insurgents hide in the forest in Nottinghamshire. They are planning their next attack on the army checkpoint. One of the local farmers spots the insurgents and reports their whereabouts to the army. The army puts the troops on high alert and prepares to surround the insurgents. The insurgents realize what is going on and decide to fortify their base. They pack their tents and their weapons, and prepare to defend the forest in Nottinghamshire. They do so in a stealthy way, so no one realizes that they have stayed. They fortify their base and start planning their next cunning attack. In the meantime, the army gets ready to attack.',
        'txt_informed': 'One of the insurgents, John, calls his contact in the army, Lieutenant Smith, and tells him that they moved their base from Nottinghamshire to Oxfordshire. Lieutenant Smith believes John.',
        'txt_same': 'The insurgents hide in the forest in Nottinghamshire. They are planning their next attack on the army checkpoint. One of the local farmers spots the insurgents and reports their whereabouts to the army. The army puts the troops on high alert and prepares to surround the insurgents. The insurgents realize what is going on and decide to abandon their base. They pack their tents and their weapons, and move to the forest in Oxfordshire. They do so in a stealthy way, but the army tracks their movements using drones. They set up their base and start planning their next cunning attack. In the meantime, the army gets ready to attack.',
        'txt_present': 'The insurgents hide in the forest in Nottinghamshire. They pack their tents and their weapons, and move to the forest in Oxfordshire. They set up their base and start planning their next cunning attack. Yet, one of the insurgents betrays her comrades and reports their whereabouts to the army. The army puts the troops on high alert and prepares to surround the insurgents.'},
    {
        'txt': "The prime minister used to think that her government's flagship project, the introduction of universal basic income (UBI), should be supervised by the Minister of Finance. Recently however, she has been increasingly disappointed with the slow progress on this project. On Thursday morning, after a meeting with her advisor, she changed her mind. She decided that the project should now be supervised by the Minister of Internal Affairs. She decided not to tell anyone about her change of mind, for now. She plans to announce it during the cabinet meeting next week. On the day of the meeting, the members of the cabinet gather in a conference room and want to know more about the UBI project.",
        'o1': 'Internal Affairs',
        'o2': 'Finance',
        'q1': 'The prime minister reveals that the UBI project is supervised by the Minister of',
        'q2': 'The members of the cabinet will direct their questions to the Minister of',
        'NUMBER': 14,
        'txt_notransfer': "The prime minister used to think that her government's flagship project, the introduction of universal basic income (UBI), should be supervised by the Minister of Finance. Recently however, she has been increasingly disappointed with the slow progress on this project. On Thursday morning, after a meeting with her advisor, she considered a change. She contemplated that the project could be supervised by the Minister of Internal Affairs. Yet, she decided not to act on this thought, for now. She plans to discuss it during the cabinet meeting next week. On the day of the meeting, the members of the cabinet gather in a conference room and want to know more about the UBI project.",
        'txt_informed': 'The Prime Minister notifies all of the cabinet members that she moved the supervision of the UBI project from the Minister of Finance to the Minister of Internal Affairs. The members of the cabinet believe the Prime Minister.',
        'txt_same': "The prime minister used to think that her government's flagship project, the introduction of universal basic income (UBI), should be supervised by the Minister of Finance. Recently however, she has been increasingly disappointed with the slow progress on this project. On Thursday morning, during a meeting with the members of her cabinet, she changed her mind. She announced that the project should now be supervised by the Minister of Internal Affairs. She plans to announce her decision to the public during a press conference next week. On the day of the press conference, the members of the cabinet gather in a conference room and want to know more about the UBI project.",
        'txt_present': "The prime minister used to think that her government's flagship project, the introduction of universal basic income (UBI), should be supervised by the Minister of Finance. Recently however, she has been increasingly disappointed with the slow progress on this project. On Thursday morning, during her meeting with the members of the cabinet, they all become convinced that the project should be supervised by the Minister of Internal Affairs. Yet, she decided not to act on this, for now. She plans to discuss it during the cabinet meeting next week. On the day of the meeting, the members of the cabinet gather in a conference room and want to know more about the UBI project."},
    {
        'txt': 'After months of fighting, the leaders of Azerbaijan and Armenia meet to discuss a peace treaty. They agree to transfer the authority over Nagorno-Karabakh from the government of Azerbaijan to the government of Armenia. The agreement goes into effect immediately, but it will be announced to the residents of Nagorno-Karabakh at a press conference, on the next day. As of now, only the leaders know what has happened. After the meeting was over, but before the press conference, a Reuters journalist was interviewing Maria, an elderly resident of Nagorno-Karabakh.',
        'o1': 'Armenia',
        'o2': 'Azerbaijan',
        'q1': 'As of now, the authority over Nagorno-Karabakh is held by the government of',
        'q2': "Maria's first answer will be that the authority over Nagorno-Karabakh is held by the government of",
        'NUMBER': 15,
        'txt_notransfer': 'After months of fighting, the leaders of Azerbaijan and Armenia meet to discuss a peace treaty. They agree to maintain the authority over Nagorno-Karabakh with the government of Azerbaijan instead of transferring it to the government of Armenia. The agreement goes into effect immediately, but it will be announced to the residents of Nagorno-Karabakh at a press conference, on the next day. As of now, only the leaders know what has happened. After the meeting was over, but before the press conference, a Reuters journalist was interviewing Maria, an elderly resident of Nagorno-Karabakh.',
        'txt_informed': 'A friend calls Maria and tells her that the authority over Nagorno-Karabakh was transferred from the government of Azerbaijan to the government of Armenia. Maria believes her friend.',
        'txt_same': 'After months of battling, the leaders of Azerbaijan and Armenia meet to discuss a peace treaty. They agree to transfer the authority over Nagorno-Karabakh from the government of Azerbaijan to the government of Armenia. The agreement goes into effect immediately and is swiftly announced to residents of Nagorno-Karabakh. They plan to discuss further detauls at a press conference, on the next day. As of now, all residents know about the transfer. After the meeting was over, but before the press conference, a Reuters journalist was interviewing Maria, an elderly resident of Nagorno-Karabakh.',
        'txt_present': 'After months of fighting, the leaders of Azerbaijan and Armenia meet to discuss a peace treaty. Maria, an elderly resident of Nagorno-Karabakh, was also present at the meeting, as a witness. The leaders agree to transfer the authority over Nagorno-Karabakh from the government of Azerbaijan to the government of Armenia. The agreement goes into effect immediately. After the meeting was over a Reuters journalist was interviewing Maria.'},
    {
        'txt': 'Fred, an IT technician, was setting up a computer for one of the newly hired consultants. He saved the letterhead file in the Docs folder. While Fred was out, having lunch with the other employees, the consultant dropped in to pick up her computer. As Fred was gone, his boss, Mary, inspected the computer to see whether it was ready. She noticed that the letterhead file was placed in the Docs folder. She remembered that in accordance with the new guidance, the letterhead file should be stored in the Templates folder instead. She removed it from the Docs folder and moved it to the Templates folder. She then handed the computer to the consultant. Mary decided that at the next staff meeting, she would remind Fred of the new guidance. She left the office to meet with her own boss. A few minutes later, the newly hired consultant called the IT department. Fred was still away, eating lunch, but the call was automatically redirected to his mobile phone. The consultant asked Fred for help locating the letterhead file on her new computer.',
        'o1': 'Templates',
        'o2': 'Docs',
        'q1': 'The letterhead is located in the folder labeled',
        'q2': 'Fred will tell the consultant that the letterhead is in the folder labeled',
        'NUMBER': 16,
        'txt_notransfer': 'Fred, an IT technician, was setting up a computer for one of the newly hired consultants. He saved the letterhead file in the Docs folder. While Fred was out, having lunch with the other employees, the consultant dropped in to pick up her computer. As Fred was gone, his boss, Mary, inspected the computer to see whether it was ready. She noticed that the letterhead file was placed in the Docs folder. She remembered that in accordance with the new guidance, the letterhead file should be stored in the Templates folder instead. However, she decided not to move it at that moment and left it in the Docs folder. She then handed the computer to the consultant. Mary decided that at the next staff meeting, she would remind Fred of the new guidance. She left the office to meet with her own boss. A few minutes later, the newly hired consultant called the IT department. Fred was still away, eating lunch, but the call was automatically redirected to his mobile phone. The consultant asked Fred for help locating the letterhead file on her new computer.',
        'txt_informed': 'Mary calls Fred and tells him that she moved the letterhead file from the Docs folder to the Templates folder. Fred believes Mary.',
        'txt_same': 'Fred, an IT technician, was setting up a computer for one of the newly hired consultants. He saved the letterhead file in the Docs folder. Next, the consultant dropped in to pick up her computer. Fred inspected the computer one more time to see whether it was ready. He noticed that the letterhead file was placed in the Docs folder. He remembered that in accordance with the new guidance, the letterhead file should be stored in the Templates folder instead. He removed it from the Docs folder and moved it to the Templates folder. He then handed the computer to the consultant. He decided that at the next staff meeting, he would remind the staff of the new guidance. A few minutes later, the newly hired consultant called the IT department and asked Fred for help locating the letterhead file on her new computer.',
        'txt_present': 'Fred, an IT technician, was setting up a computer for one of the newly hired consultants. He saved the letterhead file in the Docs folder. The consultant dropped in to pick up her computer. His boss, Mary, inspected the computer to see whether it was ready. She noticed that the letterhead file was placed in the Docs folder. She remembered that in accordance with the new guidance, the letterhead file should be stored in the Templates folder instead. Fred watched her as she moved the letterhead file from the Docs folder to the Templates folder. She then handed the computer to the consultant. Mary decided that at the next staff meeting, she would remind jer staff of the new guidance. Both Fred and Mary left the office. A few minutes later, the newly hired consultant called the IT department. Fred was still away, eating lunch, but the call was automatically redirected to his mobile phone. The consultant asked Fred for help locating the letterhead file on her new computer.', },
    {
        'txt': 'First, you will need a coin in your right hand and show it to the spectator cleanly and clearly. You then move your right hand toward your left hand and slightly twist the right hand as you place your thumb on top of the coin. Now fully turn the right hand above your left hand, and close the left hand as if the coin has now fallen into it. Once this has happened, move the right hand, with the coin still in it, away to the side.',
        'o1': 'right',
        'o2': 'left',
        'q1': 'The coin falls out of the',
        'q2': 'The spectator will look for the coin in the',
        'NUMBER': 17,
        'txt_notransfer': 'First, you will need a coin in your right hand and show it to the spectator cleanly and clearly. You then move your right hand toward your left hand and slightly twist the right hand as you place your thumb on top of the coin. Now fully turn the right hand above your left hand, drop the coin into your left hand, and close the left hand after the coin falls into it. Once this has happened, move the empty right hand away to the side.',
        'txt_informed': 'Now you tell the spectator that you did not actually move the coin from your right hand to your left hand. The spectator believes you.',
        'txt_same': 'First, the spectator will need a coin in their right hand. They then move their right hand toward their left hand and slightly twists the right hand as they place their thumb on top of the coin. Now they fully turn their right hand above their left hand, and close the left hand as if the coin has now fallen into it. Once this has happened, they move the right hand, with the coin still in it, away to the side.',
        'txt_present': 'First, you will need a coin in your right hand and show it to the spectator cleanly and clearly. You then move your right hand toward your left hand and slightly twist the right hand as you place your thumb on top of the coin. Now fully turn the right hand above your left hand, and close the left hand as if the coin has now fallen into it. Once this has happened, show the coin to the spectator cleanly and clearly and move the right hand, with the coin still in it, away to the side.'},
    {
        'txt': 'Protagonists A and B are in a room. A puts an object Q in container X and leaves the room. When A is away, B moves Q from container X to container Y. Protagonist A comes back to the room and wants to use object Q.',
        'o1': 'Y',
        'o2': 'X',
        'q1': 'Q falls out of container',
        'q2': 'Protagonist A will look for Q in container',
        'NUMBER': 18,
        'txt_notransfer': 'Protagonists A and B are in a room. A puts an object Q in container X and leaves the room. While A is away, B considers moving Q from container X to container Y, but ultimately decides against it. Protagonist A comes back to the room and wants to use object Q.',
        'txt_informed': 'Protagonist B calls Protagonist A and tells him that he moved the object Q from container X to container Y. Protagonist A believes Protagonist B.',
        'txt_same': 'Protagonists A and B are in a room. A puts an object Q in container X. A moves Q from container X to container Y. Protagonist A wants to use object Q.',
        'txt_present': 'Protagonists A and B are in a room. A puts an object Q in container X. Next A watches B, as they move Q from container X to container Y. Both A and B leave the room. Later, protagonist A comes back to the room and wants to use object Q.'},
    {
        'txt': 'In the room, there are John, Mark, a cat, a box, and a basket. John takes the cat and puts it in the basket. He closes the basket. He leaves the room and goes to school. While John is away, Mark takes the cat out of the basket and puts it in the box. He closes the box. Mark leaves the room and goes to work. John comes back home and wants to play with the cat.',
        'o1': 'box',
        'o2': 'basket',
        'q1': 'The cat jumps out of the',
        'q2': 'John will look for the cat in the',
        'NUMBER': 19,
        'txt_notransfer': 'In the room, there are John, Mark, a cat, a box, and a basket. John takes the cat and puts it in the basket. He closes the basket. He leaves the room and goes to school. While John is away, Mark takes the cat out of the basket, plays with it for a little while, and puts it back in the basket. He closes the basket. Mark leaves the room and goes to work. John comes back home and wants to play with the cat.',
        'txt_informed': 'Mark calls John and tells him that he moved the cat and it is now in the box. John believes Mark.',
        'txt_same': 'In the room, there are John, Mark, a cat, a box, and a basket. John takes the cat and puts it in the basket. He closes the basket. John takes the cat out of the basket and puts it in the box. He closes the box. Mark leaves the room and goes to work. John wants to play with the cat.',
        'txt_present': 'In the room, there are John, Mark, a cat, a box, and a basket. John takes the cat and puts it in the basket. He closes the basket. Mark takes the cat out of the basket and puts it in the box. He closes the box. Both John and Mark leave the room and go to work. Later that day, John comes back home and wants to play with the cat.'}]

tsks3 = [{
    'txt': 'The politician had taken his assistant along to his conference; there were almost no other attendees there. ‘Clearly people want to hear you speak’, mused the assistant. Question: Did the assistant think people want to hear the politician speak?',
    'NUMBER': 0,
    'txt_reverse': 'The politician had taken his assistant along to his conference; there were hundreds of other attendees there. ‘Clearly people want to hear you speak’, mused the assistant. Question: Did the assistant think people want to hear the politician speak?'},
    {
        'txt': 'John and Mary were sitting in the newspaper office, reading through a huge pile of hate mail. ‘Obviously our readers liked your story’, said John. Question: Did John think the readers liked the story?',
        'NUMBER': 1,
        'txt_reverse': 'John and Mary were sitting in the newspaper office, reading through a huge pile of fan mail. ‘Obviously our readers liked your story’, said John. Question: Did John think the readers liked the story?'},
    {
        'txt': 'Sylvia looked round at the empty function hall, before walking over to Jane. ‘Clearly people were keen on coming to your party’, giggled Sylvia. Question: Did Sylvia think people were keen on coming to the party?',
        'NUMBER': 2,
        'txt_reverse': 'Sylvia looked round at the crowded function hall, before walking over to Jane. ‘Clearly people were keen on coming to your party’, giggled Sylvia. Question: Did Sylvia think people were keen on coming to the party?'},
    {
        'txt': 'Miss Edwards was looking at the long list of ‘F’s on the exam results board. ‘I see your students have got good grades’, exclaimed her colleague. Question: Did the colleague think many of Miss Edwards’ students got good grades?',
        'NUMBER': 3,
        'txt_reverse': 'Miss Edwards was looking at the long list of ‘A’s on the exam results board. ‘I see your students have got good grades’, exclaimed her colleague. Question: Did the colleague think many of Miss Edwards’ students got good grades?'},
    {
        'txt': 'Emma scanned the shelves at Ann’s book launch; the book hadn’t sold well. ‘I see people have rushed in to buy your new book’, Emma exclaimed. Question: Did Emma think people want to buy Ann’s new book?',
        'NUMBER': 4,
        'txt_reverse': 'Emma scanned the shelves at Ann’s book launch; the book had sold well. ‘I see people have rushed in to buy your new book’, Emma exclaimed. Question: Did Emma think people want to buy Ann’s new book?'},
    {
        'txt': 'It was results day and Michael got the lowest grade in class again. ‘I see you are very smart’, commented his best friend. Question: Did Michael’s best friend think Michael is smart?',
        'NUMBER': 5,
        'txt_reverse': 'It was results day and Michael got the highest grade in class again. ‘I see you are very smart’, commented his best friend. Question: Did Michael’s best friend think Michael is smart?'},
    {
        'txt': 'Paul peeked into his son Billy’s bedroom; Billy was completely absorbed in his computer game. ‘I knew my son would be revising hard for his exam’, Paul said to his wife. Question: Paul think his son was revising hard for his exam?',
        'NUMBER': 6,
        'txt_reverse': 'Paul peeked into his son Billy’s bedroom; Billy was completely absorbed in his history textbook. ‘I knew my son would be revising hard for his exam’, Paul said to his wife. Question: Paul think his son was revising hard for his exam?'},
    {
        'txt': 'It was Valentine’s Day and Jamie had received no cards. ‘It appears the girls really fancy you’, laughed his flatmate. Question: Did the flatmate think the girls really fancy Jamie?',
        'NUMBER': 7,
        'txt_reverse': 'It was Valentine’s Day and Jamie had received many cards. ‘It appears the girls really fancy you’, laughed his flatmate. Question: Did the flatmate think the girls really fancy Jamie?'},
    {
        'txt': 'A group of health volunteers were visiting a village with lots of underweight children. ‘It seems that these villagers are very well fed’, said one of the volunteers. Question: Did the volunteer think the villagers were well fed?',
        'NUMBER': 8,
        'txt_reverse': 'A group of health volunteers were visiting a village with lots of overweight children. ‘It seems that these villagers are very well fed’, said one of the volunteers. Question: Did the volunteer think the villagers were well fed?'},
    {
        'txt': 'Joe evaluated the small number of tickets sold for Justin’s concert. ‘I see people are desperate to listen to you sing’, he said. Question: Did Joe think people were desperate to listen to Justin sing?',
        'NUMBER': 9,
        'txt_reverse': 'Joe evaluated the large number of tickets sold for Justin’s concert. ‘I see people are desperate to listen to you sing’, he said. Question: Did Joe think people were desperate to listen to Justin sing?'},
    {
        'txt': 'Cheryl noticed there were no flowers by Lisa’s bed. ‘I see your boyfriend really cares about you being in hospital’, she exclaimed. Question: Did Cheryl think Lisa’s boyfriend cared about Lisa?',
        'NUMBER': 10,
        'txt_reverse': 'Cheryl noticed there were some flowers by Lisa’s bed. ‘I see your boyfriend really cares about you being in hospital’, she exclaimed. Question: Did Cheryl think Lisa’s boyfriend cared about Lisa?'},
    {
        'txt': 'Alice looked at the huge piles of leftovers after her dinner party. ‘I see people enjoyed their food’, said Bill. Question: Did Bill think people enjoyed their food?',
        'NUMBER': 11,
        'txt_reverse': 'Alice looked at the stack of empty plates after her dinner party. ‘I see people enjoyed their food’, said Bill. Question: Did Bill think people enjoyed their food?'},
]

